version: '3'

services:
  app:
    build:
      context: ./flask_app
      dockerfile: ./dockerfile.dev
    volumes:
      - ./flask_app/src:/app  # Mount the 'src' directory into the '/app' directory in the container
    depends_on:
            database:
                condition: service_healthy
    ports:
      - '3000:5000'  # Expose Flask's default port
    networks:
      - subnet1
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
  
  database:
    build:
      context: ./database
      dockerfile : ./dockerfile
    ports:
      - '3306:5432'
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - subnet1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d traindatabase"]  ## The traindatabase comes from the init.sql file
      interval: 15s
      timeout: 10s
      retries: 3
    

networks:
    subnet1:
        ipam:
            driver: default