version: '3'

services:
  app:
    build: .
    volumes:
      - ./src:/src  # Mount the 'src' directory into the '/app' directory in the container
    ports:
      - "3000:5000"  # Expose Flask's default port
    environment:
      - FLASK_ENV=development  # This is used by Flask to enable development mode including hot-reloading

