version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile.dev
    volumes:
      - ./src:/app  # Mount the 'src' directory into the '/app' directory in the container
    ports:
      - "3000:5000"  # Expose Flask's default port
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development


